name: Fetch Lincence Data

on: workflow_dispatch

jobs:
  run:
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvm'
    - run: npm install
    - run: node enterprise.js
      env:
        GITHUB_ENTERPRISE_BILLING_TOKEN: ${{ secrets.ENTERPRISE_BILLING_TOKEN }}
        GITHUB_ENTERPRISE_NAME: ukhomeoffice
    - uses: EndBug/add-and-commit@v9
      with:
        message: 'Add enterprise json file'
        add: './public/enterprise.json'