name: Publisher

on: [push,pull_request]

jobs:
  run:
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvm'
    - run: npm install
    - run: node index.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: node enterprise.js
      env:
        GITHUB_ENTERPRISE_BILLING_TOKEN: ${{ secrets.ENTERPRISE_BILLING_TOKEN }}
        GITHUB_ENTERPRISE_NAME: ukhomeoffice
    - run: node lastUpdatedAt.js
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: crazy-max/ghaction-github-pages@v3
      with:
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
