name: Publisher

on: [push,pull_request]

jobs:
  run:
    permissions:
      contents: write
      pages: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvm'
    - run: npm install
    - run: node scripts/index.js
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_FETCH_TOKEN }}
    - run: npm run build-static && touch ./out/.nojekyll
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: crazy-max/ghaction-github-pages@v3
      with:
        build_dir: out
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
